
default: &default
  adapter: postgresql
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  port: '5432'
  username: postgres
  password: postgres
  database: ror_learn
  sslmode: disable

development:
  <<: *default
  database: postgres-dev

test:
  <<: *default
  database: postgres_test

production:
  <<: *default
  database: postgres_prod

